apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: btsr-api
  name: btsr-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: btsr-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: btsr-api
    spec:
      volumes:
        - name: api
          hostPath:
            path: /home/ubuntu/breqwatr-trilio-scheduler-replacement/btsr-api/api
            type: Directory
        - name: lib
          hostPath:
            path: /home/ubuntu/breqwatr-trilio-scheduler-replacement/btsr-lib/lib
            type: Directory
        - name: openrc-file
          hostPath:
            path: {{ required "openrc_file_path is required" .Values.openrc_file_path }}
        - name: logs-dir
          hostPath:
            path: {{ required "logs_dir is required" .Values.logs_dir }}
            type: Directory
      containers:
        - image: breqwatr/btsr-api
          imagePullPolicy: IfNotPresent  # or "Never" if building locally
          name: btsr-api
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /btsr/api
              name: api
            - mountPath: /btsr/lib
              name: lib
            - mountPath: /btsr/openrc.sh
              name: openrc-file
            - mountPath: /var/log/btsr
              name: logs-dir
