apiVersion: v1
kind: ConfigMap
metadata:
  name: btsr-tuning
data:
  concurrent_fulls_cloud: "1"
  concurrent_fulls_host: "1"
  concurrent_total_cloud: "1"
  concurrent_total_host: "1"
  nfs_speed_bytes_per_second: "375809638400"  # 350G (1024 * 1024 * 1024 * 350)
  volume_create_time_seconds: "60"
  workload_time_seconds: "60"
  fudge_factor: "1"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: btsr-backups
data:
  interval: "7"
  full_interval: "7"
  retention_days: "7"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: btsr-times
data:
  allow_weekdays: "yes"
  allow_weekends: "yes"
  allow_all_day_weekdays: "no"
  allow_all_day_weekends: "yes"
  weekday_blacklist_start_time: "08:00"
  weekday_blacklist_end_time: "18:00"
  weekend_blacklist_start_time: "08:00"
  weekend_blacklist_end_time: "18:00"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: btsr-conffiles
data:
  openrcPaths.conf: |
    [DEFAULT]
    kyle=kyle-openrc.sh
