apiVersion: batch/v1
kind: CronJob
metadata:
  name: btsr-worker-poll
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: btsr-worker
            image: breqwatr/btsr-worker
            imagePullPolicy: IfNotPresent
            command:
            - /bin/bash
            - -c
            - btsr-worker
            - save-summary
          restartPolicy: OnFailure
