apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: btsr-worker-idle
  name: btsr-worker-idle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: btsr-worker-idle
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: btsr-worker-idle
    spec:
      volumes:
        - name: openrc-file
          hostPath:
            path: {{ required "openrc_file_path is required" .Values.openrc_file_path }}
        - name: logs-dir
          hostPath:
            path: {{ required "logs_dir is required" .Values.logs_dir }}
            type: Directory
      containers:
        - image: breqwatr/btsr-worker
          imagePullPolicy: IfNotPresent  # or "Never" if building locally
          name: btsr-worker-idle
          command: ["/bin/bash","-c"]
          args: ["tail -f /dev/null"]
          volumeMounts:
            - mountPath: /btsr/openrc.sh
              name: openrc-file
            - mountPath: /var/log/btsr
              name: logs-dir
          envFrom:
            - configMapRef:
                name: btsr-scheduling
