apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: btsr-api
  name: btsr-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: btsr-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: btsr-api
    spec:
      volumes:
        - name: openrc-file
          hostPath:
            path: {{ required "openrc_file_path is required" .Values.openrc_file_path }}
      containers:
        - image: breqwatr/btsr-api
          imagePullPolicy: IfNotPresent  # or "Never" if building locally
          name: btsr-api
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /btsr/openrc.sh
              name: openrc-file
